version: '2'

services:
  zoneminder:
    build: https://github.com/QuantumObject/docker-zoneminder.git
    container_name: zoneminder
    restart: always
    ports:
      - 80:80 #change the first port to where you want it
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /etc/zoneminder/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
      - /media/homesec:/var/cache/zoneminder/events/
    shm_size: 4096M #edit it for fit your memory needs normally half of your totally memory
    privileged: true